2013-11-07 20:13:01,407 - news_logger - ERROR - 'NoneType' object is not callable
Traceback (most recent call last):
  File "news_scpeople.py", line 57, in main
    obj.main()
  File "/home/lgy/Code/lgy_git/Python/newspider/BaseNews.py", line 47, in main
    count=self.searchWrapper(count)
  File "/home/lgy/Code/lgy_git/Python/newspider/BaseNews.py", line 65, in searchWrapper
    items = self.nextPage(keyword)
  File "news_scpeople.py", line 29, in nextPage
    print soup.pretiffy()
TypeError: 'NoneType' object is not callable
2013-11-07 20:16:50,534 - news_logger - ERROR - 'NoneType' object is not callable
Traceback (most recent call last):
  File "news_scpeople.py", line 57, in main
    obj.main()
  File "/home/lgy/Code/lgy_git/Python/newspider/BaseNews.py", line 47, in main
    count=self.searchWrapper(count)
  File "/home/lgy/Code/lgy_git/Python/newspider/BaseNews.py", line 65, in searchWrapper
    items = self.nextPage(keyword)
  File "news_scpeople.py", line 29, in nextPage
    print soup.pretiffy()
TypeError: 'NoneType' object is not callable
